version: "2"
services:
  jekyll:
    container_name: 'vubdivingcenter'
    image: jekyll/jekyll:3.7
    command: jekyll serve --watch --force_polling --verbose
    ports:
    - 4000:4000
    volumes:
    - .:/srv/jekyll