name: Inschrijvingen verwerken

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */2 * * *'

jobs:
    inschrijvingen:
        name: 'Verwerk Inschrijvingen'
        runs-on: ubuntu-latest
        steps:
        -   uses: browser-actions/setup-chrome@v1
            with:
                chrome-version: 1198101
                id: setup-chrome
        -   name: Check out repository
            uses: actions/checkout@v3
            with:
                lfs: false
        -   name: Cache node modules
            uses: actions/cache@v3
            with:
                path: |
                    node_modules
                    /home/runner/.cache/puppeteer
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-
        -   name: Set timezone
            uses: szenius/set-timezone@v1.0
            with:
                timezoneLinux: "Europe/Brussels"
        -   uses: actions/setup-node@v2
            with:
                node-version: '22'
        -   name: Installing Dependencies
            run: |
                yarn install
        -   name: Process Inschrijvingen
            env:
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
                SENDGRID_FROM_EMAIL: ${{ secrets.SENDGRID_FROM_EMAIL }}
                GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
                GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
                GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
                REGISTRATION_CODE: ${{ secrets.REGISTRATION_CODE }}
            run: |
                node _scripts/inschrijvingen.js
