name: Status Inschrijvingen

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0'

jobs:
    inschrijvingen:
        name: 'Status Inschrijvingen'
        runs-on: ubuntu-latest
        steps:
        -   name: Check out repository
            uses: actions/checkout@v3
            with:
                lfs: false
        -   name: Cache node modules
            uses: actions/cache@v3
            with:
                path: |
                    node_modules
                    /home/runner/.cache/puppeteer
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-
        -   name: Set timezone
            uses: szenius/set-timezone@v1.0
            with:
                timezoneLinux: "Europe/Brussels"
        -   uses: actions/setup-node@v2
            with:
                node-version: '22'
        -   name: Installing Dependencies
            run: |
                yarn install
        -   name: Process Inschrijvingen
            env:
                MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
                MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
                MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL }}
                GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
                GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
                GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
            run: |
                node _scripts/inschrijvingen-status.js
